version: 2

jobs:
  test_angular:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/inventory-tracker-api/inventory-tracker
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
              - node_modules
      # Lint the source code
      - run:
          name: Linting
          command: npm run lint
      # Test the source code
      - run:
          name: Testing
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      # End to End test
      - run:
          name: End to End Test
          command: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

  test_rails:
    docker:
      - image: circleci/ruby:2.6.5
      - image: circleci/postgres:9.6.9-alpine
        environment:
          POSTGRES_USER: postgres

    working_directory: ~/inventory-tracker-api

    steps:
      - checkout
      - run:
          name: Install bundler gem
          command: gem install bundler

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: Run bundle install
          command: bundle install

      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/inventory-tracker-api/vendor/bundle
      - run:
          name: Run RSpec
          command: bundle exec rspec spec/
workflows:
  version: 2
  build_and_test:
    jobs:
      - test_angular
      - test_rails
